ethereumClient:
  rpcNodes:
    - "https://arb1.arbitrum.io/rpc"
  chainId: 42161	
  registry: 0x4b914A8c0Bb0896B6Ecb69ad199569332FeC5caa
  paginationChunkSize: 100
  gasLimit: 24000000
network: ethereum
disableHeartbeats: false
heartbeatPeriodSeconds: 43200
checkJobsPeriodSeconds: 10
plugins:
  - plugins/signature-scan-demo.so